name: leaderboard

on:
  schedule:
    - cron: "*/30 * * * *"
    
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: curl https://leaderboard-iej6.onrender.com/load_data
